import { motion } from 'framer-motion';
import { Download, FileJson, FileText, Image } from 'lucide-react';
import type { EnhancedTestResult } from '../types';

interface ExportResultsProps {
  result: EnhancedTestResult;
}

export function ExportResults({ result }: ExportResultsProps) {
  const exportAsJSON = () => {
    const dataStr = JSON.stringify(result, null, 2);
    const dataBlob = new Blob([dataStr], { type: 'application/json' });
    const url = URL.createObjectURL(dataBlob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `speedtest-${result.basic.id}.json`;
    link.click();
  };

  const exportAsCSV = () => {
    const csv = [
      'Metric,Value,Unit',
      `Download Speed,${result.basic.download_mbps},Mbps`,
      `Upload Speed,${result.basic.upload_mbps},Mbps`,
      `Latency,${result.basic.latency_ms},ms`,
      `Jitter,${result.basic.jitter_ms},ms`,
      result.loaded_latency ? `Idle Latency,${result.loaded_latency.idle_avg_ms},ms` : '',
      result.loaded_latency ? `Download Latency,${result.loaded_latency.download_avg_ms},ms` : '',
      result.loaded_latency ? `Upload Latency,${result.loaded_latency.upload_avg_ms},ms` : '',
      result.loaded_latency ? `Bufferbloat Grade,${result.loaded_latency.bufferbloat_grade},` : '',
      result.aim_scores ? `Gaming Score,${result.aim_scores.gaming.score},/100` : '',
      result.aim_scores ? `Streaming Score,${result.aim_scores.streaming.score},/100` : '',
      result.aim_scores ? `Video Call Score,${result.aim_scores.video_conferencing.score},/100` : '',
      result.aim_scores ? `Browsing Score,${result.aim_scores.general_browsing.score},/100` : '',
      result.aim_scores ? `Overall Score,${result.aim_scores.overall_score},/100` : '',
    ].filter(Boolean).join('\n');

    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `speedtest-${result.basic.id}.csv`;
    link.click();
  };

  const exportAsText = () => {
    const text = `SpeedTestPro Results
${'='.repeat(50)}

Test ID: ${result.basic.id}
Date: ${new Date(result.basic.timestamp).toLocaleString()}
Server: ${result.basic.server_id}

BASIC METRICS
-------------
Download: ${result.basic.download_mbps.toFixed(2)} Mbps
Upload: ${result.basic.upload_mbps.toFixed(2)} Mbps
Latency: ${result.basic.latency_ms.toFixed(2)} ms
Jitter: ${result.basic.jitter_ms.toFixed(2)} ms

${result.loaded_latency ? `
LOADED LATENCY
--------------
Idle: ${result.loaded_latency.idle_avg_ms.toFixed(2)} ms (${result.loaded_latency.idle_rpm.toFixed(0)} RPM)
Download: ${result.loaded_latency.download_avg_ms.toFixed(2)} ms (${result.loaded_latency.download_rpm.toFixed(0)} RPM)
Upload: ${result.loaded_latency.upload_avg_ms.toFixed(2)} ms (${result.loaded_latency.upload_rpm.toFixed(0)} RPM)
Bufferbloat Grade: ${result.loaded_latency.bufferbloat_grade}
` : ''}

${result.aim_scores ? `
AIM SCORES
----------
Gaming: ${result.aim_scores.gaming.score}/100 (${result.aim_scores.gaming.grade})
Streaming: ${result.aim_scores.streaming.score}/100 (${result.aim_scores.streaming.grade})
Video Calls: ${result.aim_scores.video_conferencing.score}/100 (${result.aim_scores.video_conferencing.grade})
Browsing: ${result.aim_scores.general_browsing.score}/100 (${result.aim_scores.general_browsing.grade})
Overall: ${result.aim_scores.overall_score.toFixed(0)}/100 (${result.aim_scores.overall_grade})
` : ''}

${result.ai_insights ? `
AI INSIGHTS
-----------
${result.ai_insights.summary}

Recommendations:
${result.ai_insights.recommendations.map((rec, i) => 
  `${i + 1}. [${rec.priority}] ${rec.title}\n   ${rec.description}`
).join('\n\n')}
` : ''}

Generated by SpeedTestPro - The World's Most Advanced Speed Test
`;

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `speedtest-${result.basic.id}.txt`;
    link.click();
  };

  const exportAsImage = async () => {
    // This would require html2canvas or similar library
    alert('Image export coming soon! For now, take a screenshot.');
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.7 }}
      className="bg-dark-800/50 backdrop-blur-lg rounded-2xl p-6 border border-dark-700"
    >
      <div className="flex items-center gap-3 mb-6">
        <Download className="w-6 h-6 text-primary-400" />
        <h3 className="text-xl font-bold text-white">Export Results</h3>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        <button
          onClick={exportAsJSON}
          className="flex flex-col items-center justify-center gap-2 p-4 bg-dark-900/50 rounded-lg hover:bg-dark-900/70 transition-all group"
        >
          <FileJson className="w-6 h-6 text-gray-400 group-hover:text-primary-400 transition-colors" />
          <span className="text-sm text-gray-400 group-hover:text-gray-300">JSON</span>
        </button>

        <button
          onClick={exportAsCSV}
          className="flex flex-col items-center justify-center gap-2 p-4 bg-dark-900/50 rounded-lg hover:bg-dark-900/70 transition-all group"
        >
          <FileText className="w-6 h-6 text-gray-400 group-hover:text-green-400 transition-colors" />
          <span className="text-sm text-gray-400 group-hover:text-gray-300">CSV</span>
        </button>

        <button
          onClick={exportAsText}
          className="flex flex-col items-center justify-center gap-2 p-4 bg-dark-900/50 rounded-lg hover:bg-dark-900/70 transition-all group"
        >
          <FileText className="w-6 h-6 text-gray-400 group-hover:text-blue-400 transition-colors" />
          <span className="text-sm text-gray-400 group-hover:text-gray-300">Text</span>
        </button>

        <button
          onClick={exportAsImage}
          className="flex flex-col items-center justify-center gap-2 p-4 bg-dark-900/50 rounded-lg hover:bg-dark-900/70 transition-all group"
        >
          <Image className="w-6 h-6 text-gray-400 group-hover:text-purple-400 transition-colors" />
          <span className="text-sm text-gray-400 group-hover:text-gray-300">Image</span>
        </button>
      </div>

      <div className="mt-4 p-3 bg-blue-500/10 rounded-lg border border-blue-500/20">
        <p className="text-xs text-blue-400">
          💡 Tip: Use JSON format for importing into other tools, CSV for spreadsheets, or Text for reports.
        </p>
      </div>
    </motion.div>
  );
}
